CREATE TABLE Courts (
    id INTEGER PRIMARY KEY, 
    c1 INTEGER NOT NULL DEFAULT 0,
    c2 INTEGER NOT NULL DEFAULT 0,
    c3 INTEGER NOT NULL DEFAULT 0,
    c4 INTEGER NOT NULL DEFAULT 0,
    c6 INTEGER NOT NULL DEFAULT 0,  
    cg1 INTEGER NOT NULL DEFAULT 0,
    cg2 INTEGER NOT NULL DEFAULT 0
);