CREATE TABLE Courts (
    id INTEGER PRIMARY KEY, 
    c1_sat INTEGER NOT NULL DEFAULT 0,
    c1_sun INTEGER NOT NULL DEFAULT 0,
    c2_sat INTEGER NOT NULL DEFAULT 0,
    c2_sun INTEGER NOT NULL DEFAULT 0,
    c3_sat INTEGER NOT NULL DEFAULT 0,
    c3_sun INTEGER NOT NULL DEFAULT 0,
    c4_sat INTEGER NOT NULL DEFAULT 0,
    c4_sun INTEGER NOT NULL DEFAULT 0,
    c6_sat INTEGER NOT NULL DEFAULT 0,
    c6_sun INTEGER NOT NULL DEFAULT 0,    
    cg1_sat INTEGER NOT NULL DEFAULT 0,
    cg1_sun INTEGER NOT NULL DEFAULT 0,
    cg2_sat INTEGER NOT NULL DEFAULT 0,
    cg2_sun INTEGER NOT NULL DEFAULT 0
);